AWSTemplateFormatVersion: 2010-09-09

Resources:
  SubnetVMK8S:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: <%=vpc%>
      AvailabilityZone: <%=vm_k8s_subnet_zone%>
      CidrBlock:  <%=vm_k8s_subnet_cidr%>
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Environment
          Value: <%=env_name%>
        - Key: Name
          Value: vm_k8s-subnet-<%=env_name%>
  
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open web access and ssh for maintenance
      VpcId: <%=vpc%>
      Tags:
        - Key: Environment
          Value: <%=env_name%>

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: <%=vm_k8s_instance_type%>
      ImageId: <%=vm_k8s_instance_ami%>
      KeyName: <%=vm_k8s_instance_keypair_name%>
      NetworkInterfaces:
        - DeviceIndex: '0'
          DeleteOnTermination: 'true'
          AssociatePublicIpAddress: 'true'
          SubnetId: !Ref SubnetVMK8S
          GroupSet: 
             - Ref: EC2SecurityGroup
      Tags:
        - Key: Environment
          Value: <%=env_name%>
        - Key: Name
          Value: vm-k8s-<%=env_name%>

Outputs:
  PrivateIp:
    Description: <%=env_name%> vm_k8s instance private IP
    Value: !GetAtt EC2Instance.PrivateIp
  PublicIp:
    Description: <%=env_name%> vm_k8s instance public IP
    Value: !GetAtt EC2Instance.PublicIp
  VMK8SSecurityGroupId:
    Description: <%=env_name%> vm_k8s security group identifier
    Value: !GetAtt [EC2SecurityGroup, GroupId]
  InstanceId:
    Description: <%=env_name%> vm_k8s instance identifier
    Value: !Ref "EC2Instance"
